# Generated by Django 4.0.4 on 2022-06-10 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100, verbose_name='Получил')),
                ('photo', models.ImageField(upload_to='photo/work/%Y/%m/%d', verbose_name='Фото Награды')),
                ('describe', models.TextField(blank=True, verbose_name='Описание (необязательно)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Награда ученика',
                'verbose_name_plural': 'Награды учеников',
                'ordering': ['owner'],
            },
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyProgram', models.FileField(upload_to='files/studyProgram/%Y/%m/%d/', verbose_name='Список выпускников')),
                ('timetable', models.FileField(upload_to='photo/children/%Y/%m/%d/', verbose_name='Расписание')),
                ('graduates', models.FileField(upload_to='files/graduates/%Y/%m/%d/', verbose_name='Список выпускников')),
                ('departments', models.FileField(upload_to='files/departments/%Y/%m/%d/', verbose_name='Количество отделений')),
                ('charter', models.FileField(upload_to='files/charter/%Y/%m/%d/', verbose_name='Устав школы')),
                ('inn', models.FileField(upload_to='files/inn/%Y/%m/%d/', verbose_name='ИНН')),
                ('licens', models.FileField(upload_to='files/licens/%Y/%m/%d/', verbose_name='Лицензия на образовательную ')),
                ('classrooms', models.FileField(upload_to='files/classrooms/%Y/%m/%d/', verbose_name='СПИСОК УЧЕБНЫХ КЛАССОВ')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Докментация',
                'verbose_name_plural': 'Документаций',
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('text', models.TextField(verbose_name='Текст публикации')),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('date_provide', models.DateTimeField(verbose_name='Дата проведения')),
                ('text_short', models.TextField(max_length=40, verbose_name='Короткий текст описания')),
                ('text', models.TextField(blank=True, verbose_name='Текст публикации')),
                ('photo', models.ImageField(upload_to='photo/posters/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Афиша',
                'verbose_name_plural': 'Афиши',
                'ordering': ['date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('info', models.TextField(blank=True, verbose_name='Информация')),
                ('photo', models.ImageField(blank=True, upload_to='photo/children/%Y/%m/%d/', verbose_name='Фото (необязательно)')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название работы')),
                ('photo', models.ImageField(upload_to='work/photo/%Y/%m/%d', verbose_name='Фото Работы')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Работа ученика',
                'verbose_name_plural': 'Работы учеников',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.user')),
                ('form', models.CharField(max_length=10, verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'ordering': ['form', 'name'],
            },
            bases=('main.user',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.user')),
                ('subject', models.CharField(max_length=20, verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
                'ordering': ['name'],
            },
            bases=('main.user',),
        ),
    ]
